# Generated by Django 4.1.5 on 2023-05-29 23:05

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='tif_links',
            field=jsonfield.fields.JSONField(default=None),
        ),
    ]
