# Generated by Django 4.1.4 on 2022-12-23 19:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_alter_project_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
