# Generated by Django 4.1.5 on 2023-01-16 02:02

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0005_alter_project_create_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='polygon',
            field=django.contrib.gis.db.models.fields.PolygonField(default=None, srid=4326),
        ),
        migrations.AddField(
            model_name='project',
            name='start_time',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.CharField(max_length=20000),
        ),
    ]
