# Generated by Django 4.1.5 on 2023-01-17 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0010_alter_project_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='uuid',
            field=models.UUIDField(db_index=True, default=337142498148778113504058847363953038833, editable=False, unique=True),
        ),
    ]
