# Generated by Django 4.1.5 on 2023-01-17 04:37

from django.db import migrations, models
import frontend.models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0011_alter_project_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='uuid',
        ),
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.CharField(default=frontend.models.id_gen, editable=False, max_length=12, primary_key=True, serialize=False),
        ),
    ]
